# backend/main.py
# Role: FastAPI application that serves precomputed .npy experiment data.
#       Scans DATA_DIR for SignData/DivData files and INFO_DIR for Info files,
#       builds an in-memory index on startup, and exposes REST endpoints.
# Assumptions:
#   - SignData files: DATA_DIR/{id}.npy.SignData.npy
#   - DivData files:  DATA_DIR/{id}.npy.DivData.npy
#   - Info files:     INFO_DIR/{id}.npy  (separate directory, matching notebook convention)
#   - INFO_DIR defaults to DATA_DIR if not set; set it to "data/Info" when Info files
#     live in a separate folder (as generated by the Jupyter notebooks).
#   - Missing Info files are handled gracefully: experiment still loads with empty beta_coeffs.
#   - Sentinel values 50000.0 and 1000.0 in SignData are replaced with None in output.
#   - All numpy types are converted to plain Python before JSON serialisation.

import os
import re
import logging
from pathlib import Path
from typing import Optional

import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

DATA_DIR = os.environ.get("DATA_DIR", "data/ResultsOfInterest")
# INFO_DIR: directory containing {id}.npy Info files.
# Notebooks write them to a separate "Info/" folder; set this env var accordingly.
INFO_DIR = os.environ.get("INFO_DIR", DATA_DIR)

SENTINELS = {50000.0, 1000.0}

# ---------------------------------------------------------------------------
# Pydantic models — mirror shared/types.ts exactly
# ---------------------------------------------------------------------------

class DivisorCount(BaseModel):
    divisor: int
    count: int

class SliceStats(BaseModel):
    beta_coeffs: list[float]
    antican_value: float
    antican_position: list[float]
    min_value: float
    min_position: list[float]
    max_value: float
    max_position: list[float]
    unique_divisors: list[DivisorCount]

class ExperimentMeta(BaseModel):
    id: str
    type: str        # "CSCK" | "Jeq"
    surface: str
    num_points: int
    file_index: int
    latex_label: str
    beta_coeffs: list[float]
    grid_size: int
    num_dimensions: int
    axis_values: list[list[float]]

class ExperimentList(BaseModel):
    experiments: list[ExperimentMeta]

class SliceRequest(BaseModel):
    experiment_id: str
    slider_indices: list[int]

class HeatmapSlice(BaseModel):
    sign_matrix: list[list[Optional[float]]]
    div_matrix: list[list[int]]
    title_alpha: list[float]
    stats: SliceStats

# ---------------------------------------------------------------------------
# Filename parsing
# ---------------------------------------------------------------------------

# CSCK: CSCKBlP22PointsInfo2  → type=CSCK, surface=BlP2, num_points=2, index=2
# CSCK: CSCKBlP1xP13PointsInfo4 → type=CSCK, surface=BlP1xP1, num_points=3, index=4
# CSCK: CSCKBlHirzebruch23PointsInfo1 → type=CSCK, surface=BlHirzebruch2, num_points=3, index=1
# Jeq:  JeqBlP22PointsInfo1   → type=Jeq, surface=BlP2, num_points=2, index=1
# Jeq:  JeqBlP1xP11PointsInfo3 → type=Jeq, surface=BlP1xP1, num_points=1, index=3

_ID_RE = re.compile(
    r"^(?P<type>CSCK|Jeq)"
    r"(?P<surface>BlP1xP1|BlHirzebruch2|BlP2)"
    r"(?P<num_points>\d+)PointsInfo(?P<file_index>\d+)$"
)

def parse_experiment_id(exp_id: str) -> Optional[dict]:
    m = _ID_RE.match(exp_id)
    if not m:
        return None
    return {
        "type": m.group("type"),
        "surface": m.group("surface"),
        "num_points": int(m.group("num_points")),
        "file_index": int(m.group("file_index")),
    }

def build_latex_label(exp_type: str, surface: str, num_points: int, file_index: int) -> str:
    surface_latex = {
        "BlP2": r"\mathbb{P}^2",
        "BlP1xP1": r"\mathbb{P}^1 \times \mathbb{P}^1",
        "BlHirzebruch2": r"\mathbb{F}_2",
    }.get(surface, surface)
    prefix = "cscK" if exp_type == "CSCK" else "J\\text{-eq}"
    return (
        rf"\mathrm{{{prefix}}}\ \mathrm{{Bl}}_{{{num_points}}}\,{surface_latex}"
        rf"\;[\#{file_index}]"
    )

# ---------------------------------------------------------------------------
# In-memory experiment index
# ---------------------------------------------------------------------------

class ExperimentRecord:
    __slots__ = ("sign_data", "div_data", "meta")

    def __init__(self, sign_data: np.ndarray, div_data: np.ndarray, meta: ExperimentMeta):
        self.sign_data = sign_data
        self.div_data = div_data
        self.meta = meta

_index: dict[str, ExperimentRecord] = {}

def _load_experiments(data_dir: str, info_dir: str) -> None:
    base = Path(data_dir)
    info_base = Path(info_dir)

    if not base.exists():
        logger.warning("DATA_DIR %s does not exist — no experiments loaded", data_dir)
        return

    if not info_base.exists():
        logger.warning(
            "INFO_DIR %s does not exist — all experiments will have empty beta_coeffs",
            info_dir,
        )

    sign_files = sorted(base.glob("*.SignData.npy"))
    ok = 0
    errors = 0

    for sign_path in sign_files:
        name = sign_path.name  # e.g. CSCKBlP22PointsInfo2.npy.SignData.npy
        stem = name[: -len(".SignData.npy")]          # e.g. "CSCKBlP22PointsInfo2.npy"
        exp_id = stem[: -len(".npy")] if stem.endswith(".npy") else stem

        parsed = parse_experiment_id(exp_id)
        if parsed is None:
            logger.warning("Cannot parse experiment id from: %s — skipped", name)
            errors += 1
            continue

        div_path = base / f"{stem}.DivData.npy"
        # Info file: INFO_DIR/{exp_id}.npy  (notebook convention)
        info_path = info_base / f"{exp_id}.npy"

        if not div_path.exists():
            logger.warning("Missing DivData for %s — skipped", exp_id)
            errors += 1
            continue

        try:
            sign_data = np.load(str(sign_path), allow_pickle=True)
            div_data = np.load(str(div_path), allow_pickle=True)
        except Exception as exc:
            logger.error("Failed to load SignData/DivData for %s: %s — skipped", exp_id, exc)
            errors += 1
            continue

        N = sign_data.ndim
        M = sign_data.shape[0]

        axis_values = [
            [float(v) for v in np.linspace(0.0, 1.0, M)]
            for _ in range(N)
        ]

        # beta_coeffs from Info[1] — warn if missing, continue with empty list.
        beta_coeffs: list[float] = []
        if info_path.exists():
            try:
                info = np.load(str(info_path), allow_pickle=True)
                beta_coeffs = [float(v) for v in info[1]]
            except Exception as exc:
                logger.warning("Could not read Info[1] for %s: %s", exp_id, exc)
        else:
            logger.debug("No Info file for %s (expected %s) — beta_coeffs will be empty", exp_id, info_path)

        meta = ExperimentMeta(
            id=exp_id,
            type=parsed["type"],
            surface=parsed["surface"],
            num_points=parsed["num_points"],
            file_index=parsed["file_index"],
            latex_label=build_latex_label(
                parsed["type"], parsed["surface"],
                parsed["num_points"], parsed["file_index"],
            ),
            beta_coeffs=beta_coeffs,
            grid_size=M,
            num_dimensions=N,
            axis_values=axis_values,
        )

        _index[exp_id] = ExperimentRecord(sign_data, div_data, meta)
        ok += 1

    logger.info("Loaded %d experiments; %d errors", ok, errors)

# ---------------------------------------------------------------------------
# Statistics helpers
# ---------------------------------------------------------------------------

def _compute_stats(
    sign_2d: np.ndarray,
    div_2d: np.ndarray,
    axis_b: list[float],
    axis_c: list[float],
    beta_coeffs: list[float],
) -> SliceStats:
    # Mask sentinels, NaN, and Inf so they never reach JSON serialisation.
    mask_valid = ~np.isin(sign_2d, list(SENTINELS)) & np.isfinite(sign_2d)
    valid_vals = sign_2d[mask_valid]

    # antican_value: closest to -1.0 among valid values
    if valid_vals.size == 0:
        antican_value = 0.0
        antican_pos = [0.0, 0.0]
        min_value = 0.0
        min_pos = [0.0, 0.0]
        max_value = 0.0
        max_pos = [0.0, 0.0]
    else:
        antican_idx = int(np.argmin(np.abs(valid_vals - (-1.0))))
        antican_value = float(valid_vals.flat[antican_idx])

        # Find grid position — iterate to find row/col
        flat_positions = np.argwhere(mask_valid)
        antican_pos_idx = flat_positions[antican_idx]
        antican_pos = [axis_b[antican_pos_idx[0]], axis_c[antican_pos_idx[1]]]

        # min_value: minimum where value > -1e17 (excluding sentinels)
        finite_mask = mask_valid & (sign_2d > -1e17)
        finite_vals = sign_2d[finite_mask]
        if finite_vals.size > 0:
            min_flat = int(np.argmin(finite_vals))
            min_value = float(finite_vals.flat[min_flat])
            min_positions = np.argwhere(finite_mask)
            min_pos_idx = min_positions[min_flat]
            min_pos = [axis_b[min_pos_idx[0]], axis_c[min_pos_idx[1]]]
        else:
            min_value = 0.0
            min_pos = [0.0, 0.0]

        # max_value: maximum where value < 0 (excluding sentinels)
        neg_mask = mask_valid & (sign_2d < 0.0)
        neg_vals = sign_2d[neg_mask]
        if neg_vals.size > 0:
            max_flat = int(np.argmax(neg_vals))
            max_value = float(neg_vals.flat[max_flat])
            neg_positions = np.argwhere(neg_mask)
            max_pos_idx = neg_positions[max_flat]
            max_pos = [axis_b[max_pos_idx[0]], axis_c[max_pos_idx[1]]]
        else:
            max_value = 0.0
            max_pos = [0.0, 0.0]

    # unique_divisors — coerce to int first; div_2d may be an object array
    # (pickled from notebook) containing None or strings at failure points.
    div_int = np.vectorize(lambda v: int(v) if v is not None and v != "" else 0)(div_2d)
    unique, counts = np.unique(div_int, return_counts=True)
    div_counts = [
        DivisorCount(divisor=int(d), count=int(c))
        for d, c in sorted(zip(unique, counts), key=lambda x: x[0])
        if int(d) > 0
    ]

    return SliceStats(
        beta_coeffs=beta_coeffs,
        antican_value=antican_value,
        antican_position=antican_pos,
        min_value=min_value,
        min_position=min_pos,
        max_value=max_value,
        max_position=max_pos,
        unique_divisors=div_counts,
    )

def _sign_2d_to_json(arr: np.ndarray) -> list[list[Optional[float]]]:
    rows = []
    for row in arr:
        json_row: list[Optional[float]] = []
        for val in row:
            fval = float(val)
            if fval in SENTINELS or not np.isfinite(val):
                json_row.append(None)
            else:
                json_row.append(fval)
        rows.append(json_row)
    return rows

# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------

app = FastAPI(title="CSCK/J-eq Visualisation API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.on_event("startup")
def startup() -> None:
    _load_experiments(DATA_DIR, INFO_DIR)

# Sort key: type then surface then num_points then file_index
_SURFACE_ORDER = {"BlP2": 0, "BlP1xP1": 1, "BlHirzebruch2": 2}
_TYPE_ORDER = {"CSCK": 0, "Jeq": 1}

def _sort_key(meta: ExperimentMeta) -> tuple:
    return (
        _TYPE_ORDER.get(meta.type, 99),
        _SURFACE_ORDER.get(meta.surface, 99),
        meta.num_points,
        meta.file_index,
    )

@app.get("/api/experiments", response_model=ExperimentList)
def list_experiments() -> ExperimentList:
    metas = sorted([rec.meta for rec in _index.values()], key=_sort_key)
    return ExperimentList(experiments=metas)

@app.get("/api/experiments/{experiment_id}", response_model=ExperimentMeta)
def get_experiment(experiment_id: str) -> ExperimentMeta:
    rec = _index.get(experiment_id)
    if rec is None:
        raise HTTPException(status_code=404, detail=f"Experiment {experiment_id!r} not found")
    return rec.meta

@app.post("/api/slice", response_model=HeatmapSlice)
def get_slice(req: SliceRequest) -> HeatmapSlice:
    rec = _index.get(req.experiment_id)
    if rec is None:
        raise HTTPException(status_code=404, detail=f"Experiment {req.experiment_id!r} not found")

    meta = rec.meta
    N = meta.num_dimensions
    expected_sliders = N - 2
    if len(req.slider_indices) != expected_sliders:
        raise HTTPException(
            status_code=422,
            detail=(
                f"Expected {expected_sliders} slider indices for N={N}, "
                f"got {len(req.slider_indices)}"
            ),
        )

    # Validate indices
    M = meta.grid_size
    for k, idx in enumerate(req.slider_indices):
        if not (0 <= idx < M):
            raise HTTPException(
                status_code=422,
                detail=f"Slider index {idx} out of range [0, {M-1}] for axis {k}",
            )

    # Slice: sign_data[i0, i1, …, :, :]
    sign_data = rec.sign_data
    div_data = rec.div_data

    idx_tuple = tuple(req.slider_indices)
    if expected_sliders == 0:
        sign_2d = sign_data[:, :]
        div_2d = div_data[:, :]
    else:
        sign_2d = sign_data[idx_tuple]
        div_2d = div_data[idx_tuple]

    # Ensure 2D
    if sign_2d.ndim != 2:
        raise HTTPException(status_code=500, detail="Slice did not produce a 2D array")

    axis_b = meta.axis_values[N - 2]
    axis_c = meta.axis_values[N - 1]

    stats = _compute_stats(sign_2d, div_2d, axis_b, axis_c, meta.beta_coeffs)

    title_alpha = [
        meta.axis_values[k][req.slider_indices[k]]
        for k in range(expected_sliders)
    ]

    div_int = np.vectorize(lambda v: int(v) if v is not None and v != "" else 0)(div_2d)
    return HeatmapSlice(
        sign_matrix=_sign_2d_to_json(sign_2d),
        div_matrix=[[int(v) for v in row] for row in div_int],
        title_alpha=title_alpha,
        stats=stats,
    )

@app.get("/api/health")
def health() -> dict:
    return {"status": "ok"}
